### ISSUE TITLE
Any chance to display the timeline you created horizontally?

### ISSUE THREAD

**Issue by supertrip86** [AhmedBHameed/TimeLine#1]
Hey, you really did a great job, thanks a lot! I wonder though if there could be any chance to render your timeline horizontally rather than vertically. Is that already a feature? Am I missing something? 

Many thanks

**Comment by AhmedBHameed** [comment]
Hi @supertrip86 . Thank you for your words.
I actually don't know if this might be a new feature. As you know i use here JQuery to render my DOM element in a shape i wanted.
Also this feature will be rendered only on big screen in a better scenario which the world now a day go to the mobile screens rather than big screens. So i may keep it as it is.

Thank you.
